# Generated by Django 2.1 on 2018-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(max_length=10)),
                ('original_url', models.CharField(max_length=128)),
            ],
        ),
    ]
